#!/bin/sh
set -e
# Automatically added by dh_installalternatives/13.14.1ubuntu5
if [ "$1" = "remove" ]; then
	update-alternatives --remove cyfmac43455-sdio.bin /lib/firmware/cypress/cyfmac43455-sdio-minimal.bin.zst
fi
# End automatically added section
# Automatically added by dh_installalternatives/13.14.1ubuntu5
if [ "$1" = "remove" ]; then
	update-alternatives --remove cyfmac43455-sdio.bin /lib/firmware/cypress/cyfmac43455-sdio-standard.bin.zst
fi
# End automatically added section
