#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4ubuntu3
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'pollinate.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4ubuntu3
dpkg-maintscript-helper rm_conffile /etc/init/pollinate.conf 4.27-0ubuntu1\~ pollinate -- "$@"
# End automatically added section
