#!/bin/sh
lxd_channel() {
    track="latest"

    # lxd follows a pattern of $VERSION/stable/ubuntu-$VERSION
    # default in development is "latest"
    # with major version assigned and opened prior to Ubuntu release
    # shellcheck disable=SC1091
    [ -r /etc/os-release ] && . /etc/os-release
    case "${VERSION_ID:-""}" in
      "24.04")
        track="5.21";;
      "22.04")
        track="5.0";;
      "20.04")
        track="4.0";;
      *)
        ;;
    esac
    if [ -n "${VERSION_ID:-""}" ]; then
      echo "${track}/stable/ubuntu-${VERSION_ID}"
    else
      echo "${track}/stable"
    fi
}

snap install lxd --channel="$(lxd_channel)" 1>&2
echo 1
